### PR TITLE
Updated master

### PR DESCRIPTION
**Pull request by jackbayliss**
Couldn't find any issues here, you however can move all your JS files into public/js and then you can easily define them using the asset() method. Just a little trick, rather than going into dist etc. 

Same with CSS ^

Only thing I'm questioning is your index.php, on the live version have you gone out into the folder ( I presume so?)

So if your folder with all the website folders was called unit13, it would be like... 

require __DIR__.'/../unit13/vendor/autoload.php';

$app = require_once __DIR__.'/../unit13/bootstrap/app.php';

Depending on your file structure.
If you have it may be because the server is nginx, maybe.

### CODE REVIEW

**Comment by jackbayliss** [comment]
@bladedevleoper did you manage to fix it?

**Comment by syn-code** [comment]
Nope didn't manage to fix it man, no idea. But I do think it's my htaccess.

**Comment by jackbayliss** [comment]
Did you check your index.php? If it’s nginx it could be your htacess, try look for one on stackoverflow :)

**Comment by syn-code** [comment]
Checked that which looks to the correct destination but will check the
htaccess when I get home, getting my old pc changed into running Linux an
all so will be all open source

**Pull request closed without merging**
